Repository yooooooochan/fitness-website, pull requests merged in 2022-12, with the labels that each got.

#8 feat: add more markers and pop up info
  src/components/MapComponent.jsx
Labels: ✨ Feature

#9 Init README.md
  README.md
Labels: 🎨 Design

#12 운동 리스트 표시
  package-lock.json
  src/components/ExerciseComponent.jsx
  src/components/FindExercise.jsx
Labels: ✨ Feature, 🔨 Refactor, ⚙ Setting

#11 Update readme
  README.md
Labels: ⚙ Setting

#13 style: add thumbnail.png
  thumbnail.png
Labels: 🎨 Design

#15 feat: add map marker info
  src/components/MapComponent.jsx
Labels: ✨ Feature

#16 feat: Final calory impl.
  src/components/CaloryComponent.jsx
  src/components/ExerciseComponent.jsx
  src/components/Fooddb.jsx
  src/components/MainLayout.jsx
Labels: ✨ Feature

#17 refactor: refactor CaloryComponent.jsx
  src/components/CaloryComponent.jsx
Labels: 🔧 Fix, 🔨 Refactor

#18 Readme
  README.md
Labels: ⚙ Setting

#19 Update README.md
  README.md
Labels: ⚙ Setting
