Repository yooooooochan/fitness-website, pull requests merged in 2022-11, with the labels that each got.

#1 Main layout
  .editorconfig
  src/App.js
  src/assets/images/logo.jpg
  src/components/MainLayout.jsx
Labels: 🎨 Design, ✨ Feature

#2 불필요한 파일 제거
  src/App.css
  src/App.js
  src/App.test.js
  src/index.js
  src/logo.svg
  src/reportWebVitals.js
  src/setupTests.js
Labels: 🔨 Refactor

#3 검색 기능 구현
  src/assets/fooddb_data.json
  src/assets/fooddb_name.json
  src/components/Fooddb.jsx
  src/components/MainLayout.jsx
Labels: 🎨 Design, ✨ Feature

#4 지도 컴포넌트 추가
  .gitignore
  package-lock.json
  package.json
  public/index.html
  src/components/MainLayout.jsx
  src/components/MapComponent.jsx
Labels: ✨ Feature, ⚙ Setting
